sudo: required
services:
  - docker

before_install:
  - docker build -t olajide/fib-ui-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true olajide/fib-ui-test npm test -- --coverage

after_success:
  - docker build -t folaraz/multi-client ./client
  - docker build -t folaraz/multi-nginx ./nginx
  - docker build -t folaraz/multi-server ./server
  - docker build -t folaraz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push folaraz/multi-client
  - docker push folaraz/multi-nginx
  - docker push folaraz/multi-server
  - docker push folaraz/multi-worker
