sudo: required
services:
  - docker

before_install:
  - docker build -t olajide/fib-ui-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true olajide/fib-ui-test npm test -- --coverage

after_success:
  - docker build -t olajide/multi-client ./client
  - docker build -t olajide/multi-nginx ./nginx
  - docker build -t olajide/multi-server ./server
  - docker build -t olajide/multi-worker ./worker
  # Take those images and push to docker hub
